"""init schema

Revision ID: 56078d89784e
Revises: 
Create Date: 2026-06-28 13:21:44.846643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56078d89784e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failure_type', sa.String(length=50), nullable=True),
    sa.Column('report', sa.String(length=50), nullable=True),
    sa.Column('trace_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_failure_type'), 'memories', ['failure_type'], unique=False)
    op.create_index(op.f('ix_memories_success'), 'memories', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_success'), table_name='memories')
    op.drop_index(op.f('ix_memories_failure_type'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
