"""
Code generation agent.

This agent is responsible for constructing prompts that instruct the LLM
to generate Python code. It enriches the prompt with relevant semantic
memory and previous execution feedback, allowing the model to improve
subsequent attempts.

Responsibilities:
- Build the code-generation prompt.
- Include relevant historical memory when available.
- Include previous code and critic feedback for retries.
- Support a deterministic debug mode.
"""

from agents.llm import ask_llm
from config import DEBUG_MODE


def coder_agent(
    query: str,
    memory: str,
    code: str,
    feedback: str,
    plan: str
) -> str:
    """
    Generate Python code for the given task.

    The prompt is progressively enriched with:
    - The user's original task.
    - Relevant semantic memory from previous executions.
    - Previous generated code.
    - Feedback from the critic agent.

    During development, DEBUG_MODE returns deterministic code instead of
    invoking the LLM.

    Args:
        query:
            User's programming task.

        memory:
            Relevant semantic memory retrieved from the vector database.

        code:
            Previously generated code, if this is a retry.

        feedback:
            Critic feedback explaining why the previous attempt failed.

    Returns:
        Python code generated by the language model.
    """

    # Development shortcut to avoid unnecessary LLM calls.
    if DEBUG_MODE:
        return "```print('Hello World')```"

    prompt = f"Without explanation, using Python, solve this: {query}"

    if plan:
        prompt += f"""
Plan:
{plan}
"""

    if memory:
        prompt += f"""
Relevant past memory:
{memory}
"""

    if feedback:
        prompt += f"""
Your previous code was:
{code}

Feedback:
{feedback}
"""

    return ask_llm(prompt)