"""
The planner agent is responsible for generating a plan based on the user's query.
It uses the LLM to create a structured plan that outlines the steps needed to achieve the desired outcome.
"""
from agents.llm import ask_llm

def planner_agent(query: str) -> str:
    """
    Args:
    query (str): The user's query or request.

    Returns:
    str: A structured plan generated by the LLM.
    """
    prompt = f"Break down this query into clear implementation steps: {query}"
    return ask_llm(prompt)