"""
Response generation agent.

This agent produces the final natural-language response using the
original user query and the research gathered by the researcher agent.

Responsibilities:
- Build the final response prompt.
- Combine user query and research context.
- Invoke the language model.
"""

from agents.llm import ask_llm


def responder_agent(query: str, research: str, plan: str) -> str:
    """
    Generate the final response for the user.

    Args:
        query:
            Original user request.

        research:
            Context gathered during the research phase.

        plan:
            Generated by the planner agent.

    Returns:
        Final response generated by the language model.
    """

    prompt = f"""
Query:
{query}
"""
    if plan:
        prompt += f"\nPlan:\n{plan}"
    if research:
        prompt += f"\nResearch:\n{research}\n"

    return ask_llm(prompt)