"""
Response generation agent.

This agent produces the final natural-language response using the
original user query and the research gathered by the researcher agent.

Responsibilities:
- Build the final response prompt.
- Combine user query and research context.
- Invoke the language model.
"""

from agents.llm import ask_llm


def responder_agent(query: str, research: str) -> str:
    """
    Generate the final response for the user.

    Args:
        query:
            Original user request.

        research:
            Context gathered during the research phase.

    Returns:
        Final response generated by the language model.
    """

    prompt = f"""
Query:
{query}

Research:
{research}
"""

    return ask_llm(prompt)